[project]
authors = ["Ryan Oates <ryanoatie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "system-prompt-march2025"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
gradle = ">=8.11.1,<9"
max = ">=25.2.0.dev2025031805,<26"
anthropic = ">=0.49.0,<0.50"
openai = ">=1.66.5,<2"
