-- System Prompt March 2025 Project Database Schema

-- Events table to store all system events
CREATE TABLE IF NOT EXISTS events (
    event_id SERIAL PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(100) NOT NULL,
    destination VARCHAR(100),
    payload JSON,
    metadata JSON
);

-- Technology connectors registry
CREATE TABLE IF NOT EXISTS technology_connectors (
    connector_id SERIAL PRIMARY KEY,
    technology_name VARCHAR(50) NOT NULL UNIQUE,
    enabled BOOLEAN DEFAULT TRUE,
    version VARCHAR(20),
    capabilities JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Stories generated by the system
CREATE TABLE IF NOT EXISTS stories (
    story_id SERIAL PRIMARY KEY,
    title VARCHAR(200),
    content TEXT NOT NULL,
    context VARCHAR(100),
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tags JSON
);

-- Creatures that have emerged from the gate
CREATE TABLE IF NOT EXISTS creatures (
    creature_id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    type VARCHAR(50) NOT NULL,
    properties JSON,
    capabilities JSON,
    emergence_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default technology connectors
INSERT INTO technology_connectors (technology_name, version, capabilities)
VALUES 
    ('Java', '17.0', '{"interop": true, "native_compilation": false, "type_safety": true}'),
    ('Mojo', '0.5', '{"interop": true, "native_compilation": true, "type_safety": true}'),
    ('Swift', '5.9', '{"interop": true, "native_compilation": true, "type_safety": true}'),
    ('C++', '20', '{"interop": true, "native_compilation": true, "type_safety": false}'),
    ('Python', '3.11', '{"interop": true, "native_compilation": false, "type_safety": false}'),
    ('Go', '1.21', '{"interop": true, "native_compilation": true, "type_safety": true}'),
    ('SQL', 'ANSI', '{"interop": true, "native_compilation": false, "type_safety": true}');

-- Create indices for better query performance
CREATE INDEX idx_events_type ON events(event_type);
CREATE INDEX idx_events_timestamp ON events(timestamp);
CREATE INDEX idx_events_source ON events(source);
CREATE INDEX idx_stories_generated_at ON stories(generated_at);
CREATE INDEX idx_creatures_type ON creatures(type); 